# Generated by Django 5.0.6 on 2024-07-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implovit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
    ]
