# Generated by Django 5.0.6 on 2024-07-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implovit', '0002_productimage_caption_alter_medicines_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'verbose_name': 'Медицина', 'verbose_name_plural': 'Медицина'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображения продукта'},
        ),
        migrations.AddField(
            model_name='medicines',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='implovit.producttags'),
        ),
    ]
