# Generated by Django 5.0.6 on 2024-07-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implovit', '0003_producttags_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImages',
        ),
        migrations.AlterModelOptions(
            name='producttags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
